# Generated by Django 4.2.6 on 2023-10-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("term", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
